### ISSUE TITLE
100

### ISSUE THREAD

**Issue by qwasdzxcc** [ston-fi/tonlib-rs#126]
UQC0lymzTRdR7Vqr-avoWenlcDTnOvIqp_dcXVs-5qWW_SEd

**Comment by qwasdzxcc** [comment]
UQD9Fpyr-qiPozXb-YZHqmh6vXimdZBlDU9QUqqLqsH9dlBC

**Comment by qwasdzxcc** [comment]
UQD9Fpyr-qiPozXb-YZHqmh6vXimdZBlDU9QUqqLqsH9dlBC

**Comment by qwasdzxcc** [comment]
UQC0lymzTRdR7Vqr-avoWenlcDTnOvIqp_dcXVs-5qWW_SEd

**Comment by zxcqirara** [comment]
Why are you stupid?
