### ISSUE TITLE
CAN NOT compile on MacOS m2

### ISSUE THREAD

**Issue by oneforalone** [ston-fi/tonlib-rs#47]
I'm just testing wether the lib with Jetton, however, it failed when compiling, got an error:

```
  ld: warning: ignoring duplicate libraries: 'libton_crypto_core.a'
  + cc -O2 -fno-builtin -fPIC -Wall -Wextra -Werror -c /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/server.c
  In file included from /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/server.c:7:
  In file included from /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/keygen.c:7:
  In file included from /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/consts.h:8:
  /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/vect.h:402:11: fatal error: 'stdlib.h' file not found
  # include <stdlib.h>
            ^~~~~~~~~~
  1 error generated.
  make[3]: *** [third-party/blst/libblst.a] Error 1
  make[2]: *** [CMakeFiles/blst.dir/all] Error 2
  make[1]: *** [tonlib/CMakeFiles/tonlibjson.dir/rule] Error 2
  make: *** [tonlibjson] Error 2
  thread 'main' panicked at /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 2
  ```

Seems the third-party dependency can not found stdlib.h file, while I can compile properly with a hello C codes with stdlib.h. What am i missing? Any ideas about this issue?

Here is my rust codes:
```rust
use anyhow::Result;
use tonlib::{address::TonAddress, client::TonClient, contract::TonContractFactory};

#[tokio::main]
async fn main() -> Result<()> {
    let client = TonClient::builder().build().await?;
    let contract_factory = TonContractFactory::builder(&client).build().await?;
    let bnp_addr = TonAddress::from_str("EQABTYTyiVjpvfusZeCpmMj9x1llcJLpW_oKyd8QzcPsq5Es")?;
    let bjetton_master_contract = contract_factory.get_contract(&bnp_addr);
    let jetton_data = bjetton_master_contract.get_jetton_data().await?;

    eprintln!("{:?}", jetton_data);

    Ok(())
}
```

**Comment by beborngod** [comment]
> I'm just testing wether the lib with Jetton, however, it failed when compiling, got an error:
> 
> ```
>   ld: warning: ignoring duplicate libraries: 'libton_crypto_core.a'
>   + cc -O2 -fno-builtin -fPIC -Wall -Wextra -Werror -c /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/server.c
>   In file included from /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/server.c:7:
>   In file included from /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/keygen.c:7:
>   In file included from /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/consts.h:8:
>   /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tonlib-sys-2024.1.0/ton/third-party/blst/src/vect.h:402:11: fatal error: 'stdlib.h' file not found
>   # include <stdlib.h>
>             ^~~~~~~~~~
>   1 error generated.
>   make[3]: *** [third-party/blst/libblst.a] Error 1
>   make[2]: *** [CMakeFiles/blst.dir/all] Error 2
>   make[1]: *** [tonlib/CMakeFiles/tonlibjson.dir/rule] Error 2
>   make: *** [tonlibjson] Error 2
>   thread 'main' panicked at /Users/yuki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:
> 
>   command did not execute successfully, got: exit status: 2
> ```
> 
> Seems the third-party dependency can not found stdlib.h file, while I can compile properly with a hello C codes with stdlib.h. What am i missing? Any ideas about this issue?
> 
> Here is my rust codes:
> 
> ```rust
> use anyhow::Result;
> use tonlib::{address::TonAddress, client::TonClient, contract::TonContractFactory};
> 
> #[tokio::main]
> async fn main() -> Result<()> {
>     let client = TonClient::builder().build().await?;
>     let contract_factory = TonContractFactory::builder(&client).build().await?;
>     let bnp_addr = TonAddress::from_str("EQABTYTyiVjpvfusZeCpmMj9x1llcJLpW_oKyd8QzcPsq5Es")?;
>     let bjetton_master_contract = contract_factory.get_contract(&bnp_addr);
>     let jetton_data = bjetton_master_contract.get_jetton_data().await?;
> 
>     eprintln!("{:?}", jetton_data);
> 
>     Ok(())
> }
> ```

I just cannot build this library on Mac M2 with this error: `error: failed to run custom build command for `tonlib-sys v2024.3.5``

**Comment by dbaranovstonfi** [comment]
Do you have Xcode Command Line Tools  installed?

**Comment by beborngod** [comment]
I have figured out what the issue is. You must have preinstalled next libs and components on your Mac: 
``` 
readline, secp256k1, mactex, ccache, pkgconfig, cmake, libsodium
```
To solve compiling issue on your Mac you basically need to install all the stuff with `brew` :
```
brew install --cask mactex
brew install readline secp256k1 ccache pkgconfig cmake libsodium
```

To avoid reading this issue for future users, I would recommend writing a.sh script to preinstall all of this stuff before using it. Obrigado.

**Comment by oneforalone** [comment]
> Do you have Xcode Command Line Tools installed?

Yes, I've double checked it, the Xcode Command Line Tools are already installed on my mac

**Comment by oneforalone** [comment]
> To solve compiling issue on your Mac you basically need to install all the stuff with `brew` :
> 
> ```
> brew install --cask mactex
> brew install readline secp256k1 ccache pkgconfig cmake libsodium
> ```
Thanks for your efforts, however, it does not work for me, i still got the same error.

And after inspecting the detailed outputs, i found that the build not found the cmake, so the question is, how to make the building procedure to locate the cmake program?

Here is the very beginning outputs of the error:
```
Caused by:
  process didn't exit successfully: `/Users/yuki/workspace/ton/tonlib-debug/target/debug/build/tonlib-sys-73c373d45d7282df/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=ton/CMakeLists.txt
  cargo:rerun-if-changed=build.rs
  cargo:rustc-link-search=native=/opt/homebrew/opt/openssl@3/lib
  cargo:rustc-link-search=native=/opt/homebrew/opt/libsodium/lib
  cargo:rustc-link-search=native=/opt/homebrew/opt/secp256k1/lib
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
```

**Comment by beborngod** [comment]
@oneforalone If you have installed CMake via Homebrew, it should be automatically detected. However, if this does not happen, you can manually define an environment variable for CMAKE.

Also try to clone lib and build it locally.

**Comment by ducphamle2** [comment]
@oneforalone @beborngod I got the same error, and figured out how to fix it. You need to add the following flags (replace llvm@16 with your llvm location) into .zprofile

```
export CC="/opt/homebrew/opt/llvm@16/bin/clang"
export CXX="/opt/homebrew/opt/llvm@16/bin/clang++"
```

**Comment by oneforalone** [comment]
@ducphamle2 Thanks, that works. For me, the solution is:
```
brew install llvm
cat >> .zshrc <<-EOF
export CC="$(which clang)"
export CXX="$(which clang++)"
EOF
```

**Comment by rotcan** [comment]
Adding this for future reference, for me, the solution was to add the below to path
export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
