### ISSUE TITLE
Panic when running example call_blockchain_methods

### ISSUE THREAD

**Issue by jamescarter-le** [ston-fi/tonlib-rs#66]
I'm running on Ubuntu, I get a panic when trying to run `call_blockchain_methods` locally for testing. Calling crate version `tonlib = "0.15.4"` 

On this line: 
`let block_id_ext = client.lookup_block(1, &block_id, 0, 0).await?;`

Error:
`Signal: SIGABRT (signal SIGABRT)`

Log Output:
```
tonlibjsontesting/target/debug/tonlibjsontesting
Starting
MasterchainInfo: BlocksMasterchainInfo { last: BlockIdExt { workchain: -1, shard: -9223372036854775808, seqno: 38642822, root_hash: "am1TX2WSxNSgseL55oUPD8yeOTsZ7mRP5rAYf9eIsdQ=", file_hash: "ALaiy5RpRVDqptyJrh9f2mGu+03wvk4OQQ726dFdN4g=" }, state_root_hash: [229, 220, 206, 192, 232, 149, 118, 7, 41, 226, 246, 102, 19, 83, 122, 239, 100, 226, 181, 111, 82, 243, 102, 75, 187, 177, 95, 214, 205, 174, 247, 138], init: BlockIdExt { workchain: -1, shard: 0, seqno: 0, root_hash: "F6OpKZKqvqeFp6CQmFomXNMfMj2EnaUSOXN+Mh+wVWk=", file_hash: "XplPz01CXAps5qeSWUtxcyBfdAo5zVb1N979KLSKD24=" } }
[ 0][t 3][2024-06-27 21:45:17.261379631][Status.h:559][!Tonlib][&status_.is_ok()]       [Error : 500 : LITE_SERVER_NOTREADY: cannot load proof link for (-1,8000000000000000,34835953):5695B27CD38B9BC46AB7A09967D7591AA2513B7372AE51C760DD64D682DB27A8:F28D76297E7806D24CF111110F527DED07B565693AD4B208C97C9D9419E2C4AF : not in db(during last block synchronization)]
Signal: SIGABRT (signal SIGABRT)
```

Rust is not my most proficient language, so appreciate it if you could let me know if I've done something wrong, or if there is an issue with the tonlibjson interop?

![image](https://github.com/ston-fi/tonlib-rs/assets/1643692/7556251b-ecec-47b3-a88b-8824bf00245b)

**Comment by Sild** [comment]
Hi

Do you make a connection to archive node? (`.with_connection_check(Archive)`)?

Seems you're trying to receive pretty old block: `cannot load proof link for (-1,8000000000000000,34835953)`, it could be unavailable on lite-server already.

The exception looks like be thrown from cpp lite-client, so we can't handle it properly

**Comment by jamescarter-le** [comment]
Yes looks like this could be the issue, I assumed I was pulling the latest block with `get_masterchain_info`, I was able to get it to return valid state at some point. Bit bad for the ton library to actually throw, I assumed it would return an error.

Not sure it's usable if there is the possibility of a node returning bad data and crashing my app, is this normal in the Rust world? I'm coming from C# but the tooling doesn't seem to be there for .NET

**Comment by Sild** [comment]
`tonlib-rs` uses `tonlibs-sys` under the hood, but in fact `tonlib-sys` implements rust bindings over c++ library `tonlib-json` (part of [ton](https://github.com/ton-blockchain/ton) monorepo)

As long as we call external (cpp) library in the same os process, we count on library correctness - and that's not always the true =(

Recently, we added signal handler in tonlib-rs to improve diagnostic message in such cases (not in public yet, will be released soon), but we can't restore process state after internal library error

**Comment by jamescarter-le** [comment]
Sure I understand you have no control over if the bottom library just process faults, appreciate it. Thanks for your work on the lib, probably the way to use this lib is to have your own liteserver which you can be sure will behave correctly for the tonlibjson.

I'll raise it as an issue on their Git anyway, and hopefully get this fault patched.

**Comment by jamescarter-le** [comment]
Looks like there is already an issue live on their Git: https://github.com/ton-blockchain/ton/pull/979
