### ISSUE TITLE
Support liteServer.* methods?

### ISSUE THREAD

**Issue by jamescarter-le** [ston-fi/tonlib-rs#68]
I've seen a lot of libs support smc.* methods (not sure what SMC stands for).

Like I can use smc.runGetMethod, however I can't specify the block height at which I want to pull state from.

If I have an archive node, I want to be able to do this at a specific block height to build up some history for querying.

I've seen this TL which should support this: https://raw.githubusercontent.com/ton-blockchain/ton/master/tl/generate/scheme/lite_api.tl

If you check this JS lib for ton, it supports querying via this method: https://github.com/ton-core/ton-lite-client/blob/8e7089c35aaac7b7b75833c3b68a777d1d023c84/src/client.ts#L408

Would it be possible to add this functionality to your lib? Can I just pull you repo and add new types, or is there any kind of special pre-post source gen to deal with the horrendous TL serialization behind this ADNL?

**Comment by jamescarter-le** [comment]
Is there any autogenerator used for this, or can I add methods from the above lite_api.tl to add liteServer.* support?

https://github.com/ston-fi/tonlib-rs/blob/main/src/tl/function.rs

**Comment by Sild** [comment]
All what can I say so far it won't work this way: `tonlib-rs` implements [tonlib](https://github.com/ton-blockchain/ton/blob/master/tl/generate/scheme/tonlib_api.tl) api, and it's just not possible to make [lite-api](https://github.com/ton-blockchain/ton/blob/master/tl/generate/scheme/lite_api.tl) using current codebase

But let's wait for my colleagues, I can be wrong

**Comment by jamescarter-le** [comment]
Ah okay I see what you mean, it looks like instead we need bindings for `lite-client` to achieve this.

https://github.com/ton-blockchain/ton/blob/master/lite-client/lite-client.cpp

**Comment by Sild** [comment]
Yep

You can find this libraries really helpful:

* https://github.com/broxus/ton-labs-types.git
* https://github.com/broxus/ton-labs-block.git
* https://github.com/tonstack/lite-client


They're not so hight-level, but examples are clear and by my experience work nice
