### ISSUE TITLE
Version mismatch between README and published crate

### ISSUE THREAD

**Issue by hey-researcher** [ston-fi/tonlib-rs#97]
The latest version published to https://crates.io/crates/tonlib is `tonlib = "0.17.6"`, but the Usage section in the README refers to version `0.19`: https://github.com/ston-fi/tonlib-rs#usage.

**Comment by dbaranovstonfi** [comment]
Thank you for noticing this issue. We are splittng former tonlib-rs into two crates [tonlib-core](https://crates.io/crates/tonlib-core) and  [tonlib-client](https://crates.io/search?q=tonlib-client). 

The readme will be updated soon.
